# Generated by Django 4.0.4 on 2022-11-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_tourist', models.CharField(max_length=255, verbose_name='ФИО туриста')),
                ('fio_tourist_lat', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО туриста латиницей')),
                ('passport', models.CharField(max_length=15, verbose_name='Паспорт')),
                ('passport_id', models.CharField(blank=True, max_length=19, null=True, verbose_name='Идентификационный номер')),
                ('place_issue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Орган выдавший паспорт')),
                ('date_passport_issue', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорт')),
                ('date_passport_exp', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('insurance', models.CharField(choices=[('делает самостоятельно', 'Делает самостоятельно'), ('делаем мы', 'Оформить с нашими туристами')], default='делает самостоятельно', max_length=100, verbose_name='страховка')),
                ('registration', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прописка')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoices', verbose_name='счета')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ['-date_created'],
            },
        ),
    ]
