# Generated by Django 4.0.4 on 2022-10-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fio_tourist',
            field=models.CharField(max_length=255, verbose_name='ФИО туриста'),
        ),
    ]
