# Generated by Django 4.0.4 on 2022-11-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='', verbose_name='Номер счета')),
                ('status', models.CharField(choices=[('Подтверждена', 'Подтверждена'), ('В обработке', 'В обработке'), ('Отменена', 'Отменена')], default='В обработке', max_length=20)),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен?')),
                ('tourists_qouta_adult', models.IntegerField(blank=True, null=True, verbose_name='Количество взрослых')),
                ('tourists_qouta_child', models.IntegerField(blank=True, null=True, verbose_name='Количество детей')),
                ('ammount_total', models.FloatField(blank=True, null=True, verbose_name='Итого')),
                ('comission', models.FloatField(blank=True, null=True, verbose_name='Комиссия')),
                ('ammount_to_pay', models.FloatField(blank=True, null=True, verbose_name='Итого к оплате')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='agency.agency', verbose_name='Агент')),
                ('dates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.tourdayquota', verbose_name='Даты тура')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.tours', verbose_name='Название тура')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
