# Generated by Django 4.0.4 on 2022-08-21 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('client', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='page-slug', verbose_name='Номер счета')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен?')),
                ('tourists_qouta', models.IntegerField(verbose_name='Количество туристов')),
                ('agency_comission', models.FloatField(verbose_name='Агентская Комиссия')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agency.agency', verbose_name='Агент')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client', verbose_name='Туристы')),
                ('dates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.tourdayquota', verbose_name='Даты тура')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tours.tours', verbose_name='Название тура')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
