# Generated by Django 4.0.4 on 2022-09-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='Номер счета'),
        ),
    ]
