# Generated by Django 4.0.4 on 2022-09-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_remove_agency_email'),
        ('invoices', '0002_alter_invoices_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='agency.agency', verbose_name='Агент'),
        ),
    ]
