# Generated by Django 4.0.4 on 2022-09-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('invoices', '0003_alter_invoices_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='client',
        ),
        migrations.AddField(
            model_name='invoices',
            name='client',
            field=models.ManyToManyField(to='client.client', verbose_name='Туристы'),
        ),
    ]
