# Generated by Django 4.0.4 on 2022-09-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoices_client_invoices_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='agency_comission',
            field=models.FloatField(blank=True, null=True, verbose_name='Агентская Комиссия'),
        ),
    ]
