# Generated by Django 4.0.4 on 2022-09-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoices_agency_comission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='client',
        ),
    ]
