# Generated by Django 4.0.4 on 2022-09-26 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tours_num_days'),
        ('agency', '0005_alter_agency_bank_name_alter_agency_telephones_and_more'),
        ('invoices', '0006_remove_invoices_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='agency.agency', verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tours.tours', verbose_name='Название тура'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='tourists_qouta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество туристов'),
        ),
    ]
