# Generated by Django 4.0.4 on 2022-10-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoices_agency_alter_invoices_tour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='agency_comission',
        ),
        migrations.AddField(
            model_name='invoices',
            name='ammount_to_pay',
            field=models.FloatField(blank=True, null=True, verbose_name='Итого к оплате'),
        ),
    ]
