# Generated by Django 4.0.4 on 2022-10-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_remove_invoices_agency_comission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='tourists_qouta',
        ),
        migrations.AddField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('Подтверждена', 'Подтверждена'), ('В обработке', 'В обработке'), ('Отменена', 'Отменена')], default='В обработке', max_length=20),
        ),
        migrations.AddField(
            model_name='invoices',
            name='tourists_qouta_adult',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество взрослых'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='tourists_qouta_child',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество детей'),
        ),
    ]
