# Generated by Django 4.0.4 on 2022-11-04 10:19

from django.db import migrations, models
import django.db.models.deletion
import gallery.fields
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', gallery.fields.WEBPField(blank=True, null=True, upload_to=gallery.models.image_folder, verbose_name='Image')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
