# Generated by Django 4.0.4 on 2022-08-21 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managers', '0001_initial'),
        ('client', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managers.manager', verbose_name='Менеджер')),
                ('tour', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='tours.tours', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'договор',
                'verbose_name_plural': 'договоры',
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='DogClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('dog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='dogovor.dogovor')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
    ]
