# Generated by Django 4.0.4 on 2022-11-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='tours',
            name='category',
            field=models.ManyToManyField(to='tours.categorytour', verbose_name='Тип тура'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='hotels',
            field=models.ManyToManyField(to='hotel.hotel', verbose_name='Отели'),
        ),
    ]
