# Generated by Django 4.0.4 on 2022-09-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Тип тура')),
            ],
            options={
                'verbose_name': 'Тип тура',
                'verbose_name_plural': 'Типы туров',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='tours',
            name='comission',
            field=models.IntegerField(blank=True, default=40, null=True, verbose_name='Комиссия'),
        ),
        migrations.AddField(
            model_name='tours',
            name='category',
            field=models.ManyToManyField(null=True, to='tours.categorytour'),
        ),
    ]
