# Generated by Django 4.0.4 on 2022-09-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_categorytour_alter_tours_comission_tours_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='category',
            field=models.ManyToManyField(to='tours.categorytour'),
        ),
    ]
