# Generated by Django 4.0.4 on 2022-09-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tours_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='num_days',
            field=models.IntegerField(default=1, verbose_name='Количество дней'),
        ),
    ]
