# Generated by Django 4.0.4 on 2022-10-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tours_comission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='comission',
            field=models.FloatField(blank=True, default=10, null=True, verbose_name='Комиссия %'),
        ),
    ]
