# Generated by Django 4.0.4 on 2022-11-04 14:01

from django.db import migrations, models
import django.db.models.deletion
import gallery.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_room_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-timestamp', '-updated'], 'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.AddField(
            model_name='roomtype',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Количество номеров'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='booked',
            field=models.IntegerField(default=0, verbose_name='Забронировано номеров'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание номера'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='extra_bed',
            field=models.BooleanField(default=False, verbose_name='Доп кровать'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='free',
            field=models.IntegerField(default=0, verbose_name='Свободно номеров'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Цена за ночь'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='square',
            field=models.FloatField(default=0, verbose_name='Площадь, м2'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='badges',
            field=models.ManyToManyField(to='hotel.badges', verbose_name='Значки'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='currency',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image_thumb',
            field=gallery.fields.WEBPField(blank=True, null=True, upload_to='images/hotels/%Y/%m/%d', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Стоимость от'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип номера'),
        ),
    ]
