# Generated by Django 4.0.4 on 2022-09-16 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0003_remove_agency_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='bank_bik',
            field=models.CharField(default='YYYYBY2X', max_length=8, verbose_name='Бик'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='bank_bill',
            field=models.CharField(default='BYXX YYYY XXXX XXXX XXXX XXXX XXXX', max_length=34, verbose_name='Банковский Счет'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='contract_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='sign_date_contract',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписания'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agency', to=settings.AUTH_USER_MODEL),
        ),
    ]
