# Generated by Django 4.0.4 on 2022-09-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_agency_bank_bik_alter_agency_bank_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='bank_name',
            field=models.CharField(default='Банк', max_length=32, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='telephones',
            field=models.TextField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='unp',
            field=models.CharField(default='123456789', max_length=9, verbose_name='УНП'),
        ),
    ]
